export const FETCH_DATA = 'FETCH_DATA'
export const ADD_TO_PLOT = 'ADD_TO_PLOT'
export const REMOVE_TO_PLOT = 'REMOVE_TO_PLOT'

export const ADD_TO_DESIRED_PATH = 'ADD_TO_DESIRED_PATH'
export const REMOVE_FROM_DESIRED_PATH = 'REMOVE_FROM_DESIRED_PATH'

