export const FETCH_DATA = 'FETCH_DATA'
export const ADD_TO_DESIRED_PATH = 'ADD_TO_DESIRED_PATH'
export const REMOVE_FROM_DESIRED_PATH = 'REMOVE_FROM_DESIRED_PATH'
export const ADD_TO_NODE_PATH_EDGES = 'ADD_TO_NODE_PATH_EDGES'
export const REMOVE_NODE_FROM_DESIRED_PATH = 'REMOVE_NODE_FROM_DESIRED_PATH'
export const REVERSE_DESIRED_PATH = 'REVERSE_DESIRED_PATH'






